- name: Ansible test
  hosts: localhost
  tasks:

  - name: inclide vars
    include_vars:
      dir: vars


  - name: launching AWS instance using Ansible
    ec2:
      key_name: edik2-key1
      instance_type: t2.micro
      image: ami-00399ec92321828f5
      region: us-east-2
      wait: yes
      group: edik2
      count: 1
      vpc_subnet_id: subnet-7f22a014
      assign_public_ip: yes
      aws_access_key: "{{ awsuser }}"
      aws_secret_key: "{{ awspass }}"
      assign_public_ip: yes
    register: output

  - name: get ip
    debug:
      var: output.instances[0].public_ip
  - name: add-info-to-hosts-ansible
    add_host:
      name: "{{ output.instances[0].public_ip }} "
      groups: amazon-servers-builder

- name: install default-jdk, maven, git
  hosts: amazon-servers-builder
  remote_user: ubuntu
  become: yes
  tasks:
    - name: make builder
      apt:
        name: install soft
          - default-jdk
          - maven
          - git
        state: present
        update_cache: yes

    - name: get git project
      git: repo='https://github.com/boxfuse/boxfuse-sample-java-war-hello.git' dest=/home/boxfuse-sample-java-war-hello

    - name: makewar
      shell:
        cmd: mvn -f /home/boxfuse-sample-java-war-hello/pom.xml clean package
