      key_name: edik3-key1
      instance_type: t2.micro
      image: ami-00399ec92321828f5
      region: us-east-2
      wait: yes
      group: edik3
      count: 1
      vpc_subnet_id: subnet-7f22a014
      assign_public_ip: yes
      aws_access_key: "{{ awsuser }}"
      aws_secret_key: "{{ awspass }}"
      assign_public_ip: yes
    register: output

  - name: get ip
    debug:
      var: output.instances[0].public_ip

#  - name: put-info-about-host-to ansible hosts
#    shell:
#      cmd: echo "{{ output.instances[0].public_ip }}" >> /etc/ansible/hosts & echo "[awsbuilder]" >> /etc/ansible/hosts

  - name: Pause for 5 minutes to build app cache
    pause:
      minutes: 1



  - name: add-info-to-hosts-ansible
    add_host:
      name: "{{ output.instances[0].public_ip }}"
      groups: awsbuilder

- name: install default-jdk, maven, git
  hosts: awsbuilder
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure package
    apt:
      pkg:
      - default-jdk
      - maven
      - git

  - name: get git project
    git: repo='https://github.com/tarekkhoury/mywebapplication.git' dest=/home/mywebapplication


  - name: make war
    shell:
      cmd:  mvn -f /home/mywebapplication/pom.xml clean package
# ansible-playbook ap.yml  --ask-vault-pass
