# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      key_name: edik
      instance_type: t2.micro
      image: ami-00399ec92321828f5
      region: us-east-2
      wait: yes
      #  group: Ansible
      count: 1
      vpc_subnet_id: subnet-7f22a014
      assign_public_ip: yes
      aws_access_key: tamtamamtamtamtsm
      aws_secret_key: abcdefgefgefg
